name: "Movie Repository"
version: "1.0.0"
description: "A repository of movies using the Relay protocol."
client:
  hooks:
    get:
      path: hooks/client/get-client.jsx
server:
  hooks:
    pre-commit:
      path: hooks/server/pre-commit.mjs
    pre-receive:
      path: hooks/server/pre-receive.mjs
git:
  # Auto-push facilitates P2P synchronization between peers
  autoPush:
    branches: [ "main", "staging", "develop" ]
    originList:
      - "node-dfw1.relaynet.online"
      - "node-dfw2.relaynet.online"
    debounceSeconds: 2
  
  # Branch rules are enforced natively by the Rust hook dispatcher
  branchRules:
    default:
      requireSigned: false
      allowedKeys: [ ".ssh/*" ]
    branches:
      - name: main
        rule:
          requireSigned: false
          allowedKeys: [ ".ssh/id_rsa.pub" ]
      - name: public
        rule:
          allowUnsigned: true
  github:
    enabled: true
    path: "/hooks/github"
    events: [ "push" ]

